// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sum_matrixes_cuda
Rcpp::NumericMatrix sum_matrixes_cuda(Rcpp::NumericMatrix A, Rcpp::NumericMatrix B, Rcpp::NumericMatrix C, int N, int block1, int block2);
RcppExport SEXP _rparallelcuda_sum_matrixes_cuda(SEXP ASEXP, SEXP BSEXP, SEXP CSEXP, SEXP NSEXP, SEXP block1SEXP, SEXP block2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type B(BSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type C(CSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type block1(block1SEXP);
    Rcpp::traits::input_parameter< int >::type block2(block2SEXP);
    rcpp_result_gen = Rcpp::wrap(sum_matrixes_cuda(A, B, C, N, block1, block2));
    return rcpp_result_gen;
END_RCPP
}
// sum_matrixes_rcpp
Rcpp::NumericMatrix sum_matrixes_rcpp(Rcpp::NumericMatrix A, Rcpp::NumericMatrix B, Rcpp::NumericMatrix C, int N);
RcppExport SEXP _rparallelcuda_sum_matrixes_rcpp(SEXP ASEXP, SEXP BSEXP, SEXP CSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type B(BSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type C(CSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(sum_matrixes_rcpp(A, B, C, N));
    return rcpp_result_gen;
END_RCPP
}
// sum_matrixes_tbb_cuda
Rcpp::NumericMatrix sum_matrixes_tbb_cuda(Rcpp::NumericMatrix A, Rcpp::NumericMatrix B, Rcpp::NumericMatrix C, int N, int block1, int block2);
RcppExport SEXP _rparallelcuda_sum_matrixes_tbb_cuda(SEXP ASEXP, SEXP BSEXP, SEXP CSEXP, SEXP NSEXP, SEXP block1SEXP, SEXP block2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type B(BSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type C(CSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type block1(block1SEXP);
    Rcpp::traits::input_parameter< int >::type block2(block2SEXP);
    rcpp_result_gen = Rcpp::wrap(sum_matrixes_tbb_cuda(A, B, C, N, block1, block2));
    return rcpp_result_gen;
END_RCPP
}
// sum_matrixes_tbb_graph
Rcpp::NumericMatrix sum_matrixes_tbb_graph(Rcpp::NumericMatrix A, Rcpp::NumericMatrix B, Rcpp::NumericMatrix C, int N);
RcppExport SEXP _rparallelcuda_sum_matrixes_tbb_graph(SEXP ASEXP, SEXP BSEXP, SEXP CSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type B(BSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type C(CSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(sum_matrixes_tbb_graph(A, B, C, N));
    return rcpp_result_gen;
END_RCPP
}
// sum_matrixes_tbb_parallel
Rcpp::NumericMatrix sum_matrixes_tbb_parallel(Rcpp::NumericMatrix A, Rcpp::NumericMatrix B, Rcpp::NumericMatrix C, int N);
RcppExport SEXP _rparallelcuda_sum_matrixes_tbb_parallel(SEXP ASEXP, SEXP BSEXP, SEXP CSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type B(BSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type C(CSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(sum_matrixes_tbb_parallel(A, B, C, N));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rparallelcuda_sum_matrixes_cuda", (DL_FUNC) &_rparallelcuda_sum_matrixes_cuda, 6},
    {"_rparallelcuda_sum_matrixes_rcpp", (DL_FUNC) &_rparallelcuda_sum_matrixes_rcpp, 4},
    {"_rparallelcuda_sum_matrixes_tbb_cuda", (DL_FUNC) &_rparallelcuda_sum_matrixes_tbb_cuda, 6},
    {"_rparallelcuda_sum_matrixes_tbb_graph", (DL_FUNC) &_rparallelcuda_sum_matrixes_tbb_graph, 4},
    {"_rparallelcuda_sum_matrixes_tbb_parallel", (DL_FUNC) &_rparallelcuda_sum_matrixes_tbb_parallel, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_rparallelcuda(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
