# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Executes a distributed paralellel sum with RcpParallel
#' @param A `vector` array of input numbers
#' @param B `vector` array of input numbers
#' @param C `vector` array of input numbers
#' @param N `numeric` of array, default based on L2 Cache
#' @export
sum_matrixes_rcpp <- function(A, B, C, N) {
    .Call(`_rparallelcuda_sum_matrixes_rcpp`, A, B, C, N)
}

#' TBB parallelism function using a graph of nodes
#' @param A `vector` array of input numbers
#' @param B `vector` array of input numbers
#' @param C `vector` array of input numbers
#' @param N `numeric` of array, default based on L2 Cache
#' @export
sum_matrixes_tbb_graph <- function(A, B, C, N) {
    .Call(`_rparallelcuda_sum_matrixes_tbb_graph`, A, B, C, N)
}

#' TBB using parallel for
#' @param A `vector` array of input numbers
#' @param B `vector` array of input numbers
#' @param C `vector` array of input numbers
#' @param N `numeric` of array, default based on L2 Cache
#' @export
sum_matrixes_tbb_parallel <- function(A, B, C, N) {
    .Call(`_rparallelcuda_sum_matrixes_tbb_parallel`, A, B, C, N)
}

sum_matrixes_tbb_reduce <- function(A, B, C, result, N) {
    .Call(`_rparallelcuda_sum_matrixes_tbb_reduce`, A, B, C, result, N)
}

