# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Function to sum matrixes using TBB and CUDA
#' @param A `matrix` array of input numbers
#' @param B `matrix` array of input numbers
#' @param C `matrix` array of input numbers
#' @param N `numeric` of array, default based on L2 Cache
#' @param block1 `numeric` size of block 1
#' @param block2 `numeric` size of block 2
#' @export
sum_matrixes_cuda <- function(A, B, C, N, block1 = 16L, block2 = 16L) {
    .Call(`_rparallelcuda_sum_matrixes_cuda`, A, B, C, N, block1, block2)
}

#' Executes a distributed paralellel sum with RcpParallel
#' @param A `vector` array of input numbers
#' @param B `vector` array of input numbers
#' @param C `vector` array of input numbers
#' @param N `numeric` of array, default based on L2 Cache
#' @export
sum_matrixes_rcpp <- function(A, B, C, N) {
    .Call(`_rparallelcuda_sum_matrixes_rcpp`, A, B, C, N)
}

#' Function to sum matrixes using TBB and CUDA
#' @param A `matrix` array of input numbers
#' @param B `matrix` array of input numbers
#' @param C `matrix` array of input numbers
#' @param N `numeric` of array, default based on L2 Cache
#' @param block1 `numeric` size of block 1
#' @param block2 `numeric` size of block 2
#' @export
sum_matrixes_tbb_cuda <- function(A, B, C, N, block1 = 16L, block2 = 16L) {
    .Call(`_rparallelcuda_sum_matrixes_tbb_cuda`, A, B, C, N, block1, block2)
}

#' TBB parallelism function using a graph of nodes
#' @param A `vector` array of input numbers
#' @param B `vector` array of input numbers
#' @param C `vector` array of input numbers
#' @param N `numeric` of array, default based on L2 Cache
#' @export
sum_matrixes_tbb_graph <- function(A, B, C, N) {
    .Call(`_rparallelcuda_sum_matrixes_tbb_graph`, A, B, C, N)
}

#' TBB using parallel for
#' @param A `vector` array of input numbers
#' @param B `vector` array of input numbers
#' @param C `vector` array of input numbers
#' @param N `numeric` of array, default based on L2 Cache
#' @export
sum_matrixes_tbb_parallel <- function(A, B, C, N) {
    .Call(`_rparallelcuda_sum_matrixes_tbb_parallel`, A, B, C, N)
}

